site_name: Logging HTTP Client
site_url: https://pypi.org/project/logging-http-client/
repo_url: https://github.com/u-ways/logging-http-client/
docs_dir: ../../docs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Drop-in Replacement for requests: replacement_for_requests.md
    - Using the HTTP Client with Reusable Sessions: reusable_sessions.md
    - Custom Logging Hooks: custom_logging_hooks.md
    - Default Logging Configurations: default_logging_configurations.md
    - Obscuring Sensitive Data: obscuring_sensitive_data.md
  - Reference: 
    - Log Record Structure: log_record_structure.md

theme: material